# Generated by Django 3.1.13 on 2021-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(help_text='Would also act as token for the assignment', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('daily_calorie_threshold', models.DecimalField(decimal_places=2, default=2100, help_text='Calorie limit per day as set by the user, units is Cal.', max_digits=10)),
                ('daily_price_threshold', models.DecimalField(decimal_places=2, default=1000, help_text='Price limit per day as set by the user, units is USD.', max_digits=10)),
                ('role', models.CharField(choices=[('Admin', 'ADMIN'), ('Routine', 'ROUTINE')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
